#!/usr/bin/env python3
"""Render inventory and DHCP settings as a Windows PowerShell script.

Output is a .ps1 file. The supervisor copies it to the Windows DHCP server and
runs it as Administrator. The script is idempotent: re-running it after a
change to inventory.yaml updates only what's different.

Usage:
    python3 scripts/apply_dhcp_reservations.py [--output dhcp_reservations.ps1]

PowerShell is generated locally because WinRM is not configured on the DHCP
server. An administrator reviews and runs the output on Windows.
"""

import argparse
import sys
from pathlib import Path
from typing import Any, Dict, List

import yaml


REPO_ROOT = Path(__file__).resolve().parent.parent
INVENTORY_FILE = REPO_ROOT / "infra" / "inventory.yaml"
RESERVATIONS_FILE = REPO_ROOT / "infra" / "dhcp_reservations.yaml"


def load_yaml(path: Path) -> Dict[str, Any]:
    if not path.exists():
        sys.exit(f"ERROR: {path} not found")
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def normalise_mac(mac: str) -> str:
    """Convert any reasonable MAC format into the dash-separated form Windows
    DHCP expects: AA-BB-CC-DD-EE-FF."""
    cleaned = mac.replace(":", "").replace("-", "").replace(".", "").upper()
    if len(cleaned) != 12:
        raise ValueError(f"MAC '{mac}' is not 12 hex chars after stripping separators")
    return "-".join(cleaned[i:i + 2] for i in range(0, 12, 2))


def render_powershell(inventory: List[Dict[str, Any]], scope: Dict[str, Any]) -> str:
    """Generate the PowerShell script."""
    lines = []
    lines.append("# AUTO-GENERATED by scripts/apply_dhcp_reservations.py: do not edit by hand.")
    lines.append("# Inputs: infra/inventory.yaml + infra/dhcp_reservations.yaml")
    lines.append("# Run as Administrator on the Windows DHCP server.")
    lines.append("")
    lines.append("Set-StrictMode -Version Latest")
    lines.append("$ErrorActionPreference = 'Stop'")
    lines.append("")
    lines.append("# Confirm DHCP module available")
    lines.append("Import-Module DhcpServer -ErrorAction Stop")
    lines.append("")

    scope_id = scope.get("subnet", "TODO").split("/")[0]  # network address
    if scope_id == "TODO":
        lines.append("# WARNING: scope subnet is set to TODO in dhcp_reservations.yaml")
        lines.append("# Edit that file to set the actual OOB subnet before running.")
        lines.append("")

    lines.append(f"$ScopeId = '{scope_id}'")
    lines.append("")
    lines.append("# Reservations")
    lines.append("")

    devices_with_macs = [d for d in inventory if d.get("mac") and d["mac"] != "TODO"]
    devices_pending = [d for d in inventory if not d.get("mac") or d["mac"] == "TODO"]

    if not devices_with_macs:
        lines.append("# No devices have MACs collected yet: nothing to render.")
        lines.append(f"# {len(devices_pending)} device(s) pending MAC collection.")
        return "\n".join(lines) + "\n"

    for device in devices_with_macs:
        try:
            mac = normalise_mac(device["mac"])
        except ValueError as e:
            lines.append(f"# SKIP {device['name']}: {e}")
            continue

        ip = device["mgmt_ip"]
        name = device["name"]
        desc = f"OOB management: rack {device['rack']} side {device['side']}"

        lines.append(f"# {name}")
        lines.append("try {")
        lines.append(f"  Remove-DhcpServerv4Reservation -ScopeId $ScopeId -ClientId '{mac}' -ErrorAction SilentlyContinue")
        lines.append(f"  Add-DhcpServerv4Reservation -ScopeId $ScopeId -IPAddress '{ip}' -ClientId '{mac}' -Name '{name}' -Description '{desc}'")
        lines.append(f"  Write-Host 'OK: {name} {ip} {mac}'")
        lines.append("} catch {")
        lines.append(f"  Write-Host \"FAIL: {name} - $_\" -ForegroundColor Red")
        lines.append("}")
        lines.append("")

    if devices_pending:
        lines.append("# Pending devices (MAC not yet collected)")
        lines.append("")
        for d in devices_pending:
            lines.append(f"# TODO: {d['name']} ({d['mgmt_ip']}): collect MAC, add to inventory.yaml, re-render")

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default="dhcp_reservations.ps1",
                        help="Output PowerShell file (default: dhcp_reservations.ps1)")
    args = parser.parse_args()

    inv_data = load_yaml(INVENTORY_FILE)
    res_data = load_yaml(RESERVATIONS_FILE)

    inventory = inv_data.get("devices") or []
    scope = res_data.get("scope") or {}

    if not inventory:
        sys.exit("ERROR: inventory.yaml has no devices")

    output = render_powershell(inventory, scope)
    Path(args.output).write_text(output, encoding="utf-8")
    print(f"Wrote {args.output}: {len(inventory)} device(s) processed")
    print(f"Run on the Windows DHCP server as Administrator: .\\{args.output}")


if __name__ == "__main__":
    main()
